// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a.vue')['default']
    Error: typeof import('./src/views/error/Index.vue')['default']
    FreshGoods: typeof import('./src/components/FreshGoods.vue')['default']
    GoodsDetailPage: typeof import('./src/views/goods/GoodsDetailPage.vue')['default']
    GoodsImages: typeof import('./src/views/goods/components/GoodsImages.vue')['default']
    GoodsInfo: typeof import('./src/views/goods/components/GoodsInfo.vue')['default']
    GoodsItem: typeof import('./src/components/GoodsItem.vue')['default']
    GoodsItems: typeof import('./src/views/category/components/GoodsItems.vue')['default']
    GoodsList: typeof import('./src/components/GoodsList.vue')['default']
    GoodsSales: typeof import('./src/views/goods/components/GoodsSales.vue')['default']
    GoodsSku: typeof import('./src/views/goods/components/GoodsSku.vue')['default']
    Home: typeof import('./src/views/home/home.vue')['default']
    HomeBanner: typeof import('./src/components/HomeBanner.vue')['default']
    HomeCategory: typeof import('./src/views/home/components/HomeCategory.vue')['default']
    HomeGoods: typeof import('./src/components/HomeGoods.vue')['default']
    HomePage: typeof import('./src/views/home/components/HomePage.vue')['default']
    HomePanel: typeof import('./src/components/HomePanel.vue')['default']
    HomeSkeleton: typeof import('./src/components/HomeSkeleton.vue')['default']
    HomeSpecial: typeof import('./src/components/HomeSpecial.vue')['default']
    HotBrands: typeof import('./src/components/HotBrands.vue')['default']
    HotRecommends: typeof import('./src/components/HotRecommends.vue')['default']
    Index: typeof import('./src/views/error/Index.vue')['default']
    RecommendsGoods: typeof import('./src/views/category/components/RecommendsGoods.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategoryFilter: typeof import('./src/views/category/components/SubCategoryFilter.vue')['default']
    SubCategoryPage: typeof import('./src/views/category/SubCategoryPage.vue')['default']
    SubCategoryPages: typeof import('./src/views/category/components/SubCategoryPages.vue')['default']
    SubCategorySort: typeof import('./src/views/category/components/SubCategorySort.vue')['default']
    TopCategoryPage: typeof import('./src/views/category/TopCategoryPage.vue')['default']
    XtxBread: typeof import('./src/components/XtxBread.vue')['default']
    XtxBreadItem: typeof import('./src/components/XtxBreadItem.vue')['default']
    XtxCarousel: typeof import('./src/components/XtxCarousel.vue')['default']
    XtxCheckbox: typeof import('./src/components/XtxCheckbox.vue')['default']
    XtxCity: typeof import('./src/components/XtxCity.vue')['default']
    XtxFooter: typeof import('./src/components/XtxFooter.vue')['default']
    XtxHeader: typeof import('./src/components/XtxHeader.vue')['default']
    XtxHeaderNav: typeof import('./src/components/XtxHeaderNav.vue')['default']
    XtxHeaderSticky: typeof import('./src/components/XtxHeaderSticky.vue')['default']
    XtxInfiniteLoading: typeof import('./src/components/XtxInfiniteLoading.vue')['default']
    XtxLayout: typeof import('./src/components/XtxLayout.vue')['default']
    XtxMore: typeof import('./src/components/XtxMore.vue')['default']
    XtxSkeleton: typeof import('./src/components/XtxSkeleton.vue')['default']
    XtxTopNav: typeof import('./src/components/XtxTopNav.vue')['default']
  }
}
