// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FreshGoods: typeof import('./src/components/FreshGoods.vue')['default']
    GoodsItem: typeof import('./src/components/GoodsItem.vue')['default']
    Home: typeof import('./src/views/home/home.vue')['default']
    HomeBanner: typeof import('./src/components/HomeBanner.vue')['default']
    HomeCategory: typeof import('./src/views/home/components/HomeCategory.vue')['default']
    HomeGoods: typeof import('./src/components/HomeGoods.vue')['default']
    HomePage: typeof import('./src/views/home/components/HomePage.vue')['default']
    HomePanel: typeof import('./src/components/HomePanel.vue')['default']
    HomeSkeleton: typeof import('./src/components/HomeSkeleton.vue')['default']
    HomeSpecial: typeof import('./src/components/HomeSpecial.vue')['default']
    HotBrands: typeof import('./src/components/HotBrands.vue')['default']
    HotRecommends: typeof import('./src/components/HotRecommends.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategoryPage: typeof import('./src/views/category/SubCategoryPage.vue')['default']
    TopCategoryPage: typeof import('./src/views/category/TopCategoryPage.vue')['default']
    XtxCarousel: typeof import('./src/components/XtxCarousel.vue')['default']
    XtxFooter: typeof import('./src/components/XtxFooter.vue')['default']
    XtxHeader: typeof import('./src/components/XtxHeader.vue')['default']
    XtxHeaderNav: typeof import('./src/components/XtxHeaderNav.vue')['default']
    XtxHeaderSticky: typeof import('./src/components/XtxHeaderSticky.vue')['default']
    XtxLayout: typeof import('./src/components/XtxLayout.vue')['default']
    XtxMore: typeof import('./src/components/XtxMore.vue')['default']
    XtxSkeleton: typeof import('./src/components/XtxSkeleton.vue')['default']
    XtxTopNav: typeof import('./src/components/XtxTopNav.vue')['default']
  }
}
